version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@11.6.1
  shellcheck: circleci/shellcheck@3.2.0
  cypress: cypress-io/cypress@3.4.0
  node: circleci/node@5

filters: &filters
  tags:
    only: /.*/

jobs:
  testing-pnpm-node-orb:
    resource_class: small
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-pnpm: true
          pnpm-version: "9.7.1"
      - node/install-packages:
          app-dir: "examples/pnpm-install"
          pkg-manager: "pnpm"
  testing-pnpm-cypress:
    resource_class: small
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - cypress/install:
          working-directory: examples/pnpm-install
          cypress-cache-key: cypress-cache{{ arch }}-{{ checksum "examples/pnpm-install/package.json" }}
          include-branch-in-node-cache-key: true
          package-manager: "pnpm"
          post-install: "pnpm --version"

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          filters: *filters
      - shellcheck/check:
          filters: *filters
#      - cypress/run:
#          filters: *filters
#          name: Pnpm Version Example
#          node-version: "20.6"
#          working-directory: examples/pnpm-install
#          cypress-cache-key: cypress-cache{{ arch }}-{{ checksum "examples/pnpm-install/package.json" }}
#          install-command: "node --version && pnpm --version && pnpm install"
#          post-install: "./check-pnpm-version.sh 9.7.1 && npx cypress install"
#          package-manager: "pnpm"
##          package-manager-version: "9.7.1"
      - testing-pnpm-node-orb
      - testing-pnpm-cypress:
          filters: *filters