version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@11.6.1
  shellcheck: circleci/shellcheck@3.2.0
  cypress: cypress-io/cypress@3.4.0
  node: circleci/node@6

filters: &filters
  tags:
    only: /.*/

resource_class: small

jobs:
  testing-pnpm:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          install-pnpm: true
      - node/install-packages:
          override-ci-command: "pnpm install"
          app-dir: "examples/pnpm-install"
          pkg-manager: "pnpm"


workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          filters: *filters
      - shellcheck/check:
          filters: *filters
#      - cypress/run:
#          filters: *filters
#          name: Pnpm Version Example
#          node-version: "20.6"
#          working-directory: examples/pnpm-install
#          cypress-cache-key: cypress-cache{{ arch }}-{{ checksum "examples/pnpm-install/package.json" }}
#          install-command: "node --version && pnpm --version && pnpm install"
#          post-install: "./check-pnpm-version.sh 9.7.1 && npx cypress install"
#          package-manager: "pnpm"
##          package-manager-version: "9.7.1"
      - testing-pnpm